language: generic
sudo: required
env:
  global:
  - PATH="$HOME/terraform:$PATH"
before_install:
- openssl aes-256-cbc -K $encrypted_5e8d8e67061d_key -iv $encrypted_5e8d8e67061d_iv
  -in terraform.tfvars.enc -out terraform.tfvars -d
- mkdir $HOME/terraform
- cd $HOME/terraform
- curl -OL https://dl.bintray.com/mitchellh/terraform/terraform_0.6.4_linux_amd64.zip
install:
- unzip terraform_0.6.4_linux_amd64.zip
before_script:
- cd $HOME/build/ONSdigital/eq-terraform
script:
- terraform plan -var 'env=nightly-build'
