language: generic

apt:
  packages:
  - unzip

env:
  global:

before_install:
	- mkdir $HOME/terraform
	- cd $HOME/terraform
	- curl https://dl.bintray.com/mitchellh/terraform/terraform_0.6.4_linux_amd64.zip
install:
	- unzip terraform_0.6.4_linux_amd64.zip

